---

- name: Manage main configuration
  become: True
  template:
    src: "{{ role_path }}/templates/clamd.conf.j2"
    dest: "{{ clamav_config_folder }}/clamd.conf"
    owner: "{{ clamav_config_owner }}"
    group: "{{ clamav_config_group }}"
    mode: "{{ clamav_config_mode }}"
  notify: 'Restart clamd'


- name: Manage freshv configuration
  become: True
  template:
    src: "{{ role_path }}/templates/freshclam.conf.j2"
    dest: "{{ clamav_config_folder }}/freshclam.conf"
    owner: "{{ clamav_config_owner }}"
    group: "{{ clamav_config_group }}"
    mode: "{{ clamav_config_mode }}"
  notify: 'Restart freshclam'
