---

# Main tasks file for clamav role

- name: Load OS specific variables
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'install'
    - 'clamav'


- name: Execute installation tasks
  include: "{{ role_path }}/tasks/install.yml"
  tags:
    - 'install'
    - 'clamav'


- name: Execute configuration tasks
  include: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'configure'
    - 'clamav'


- name: Update Clamav signatures if packages updated
  become: True
  command: >
    {{ clamav_freshclam_binary }} -u {{ clamav_config_owner }}
      --datadir {{ clamav_clamd_database_directory }}
  when: "{{ clamav_install_user_packages.changed
            or clamav_install_default_packages.changed }}"
  tags:
    - 'configure'
    - 'clamav'


- name: Create crontabs
  include: "{{ role_path }}/tasks/crontab.yml"
  tags:
    - 'configure'
    - 'clamav'


- name: Create logrotate configuration
  become: True
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ clamav_logrotate_config }}"
  tags:
    - 'configure'
    - 'clamav'
