---

# Main tasks file for clamav role

- name: Load OS specific variables
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'install'
    - 'clamav'


- name: Execute installation tasks
  include: "{{ role_path }}/tasks/install.yml"
  tags:
    - 'install'
    - 'clamav'
