---

# Handlers main file for clamav role

- name: 'HANDLER | Restart clamd'
  become: True
  service:
    name: "{{ clamav_clamd_service_name }}"
    state: 'restarted'
  tags:
    - 'role::clamav'
    - 'role::clamav::config'
    - 'role::clamav::install'


- name: 'HANDLER | Restart freshclam'
  become: True
  service:
    name: "{{ clamav_freshclam_service_name }}"
    state: 'restarted'
  tags:
    - 'role::clamav'
    - 'role::clamav::config'
    - 'role::clamav::install'
